revoke delete on table "public"."users_table" from "anon";

revoke insert on table "public"."users_table" from "anon";

revoke references on table "public"."users_table" from "anon";

revoke select on table "public"."users_table" from "anon";

revoke trigger on table "public"."users_table" from "anon";

revoke truncate on table "public"."users_table" from "anon";

revoke update on table "public"."users_table" from "anon";

revoke delete on table "public"."users_table" from "authenticated";

revoke insert on table "public"."users_table" from "authenticated";

revoke references on table "public"."users_table" from "authenticated";

revoke select on table "public"."users_table" from "authenticated";

revoke trigger on table "public"."users_table" from "authenticated";

revoke truncate on table "public"."users_table" from "authenticated";

revoke update on table "public"."users_table" from "authenticated";

revoke delete on table "public"."users_table" from "service_role";

revoke insert on table "public"."users_table" from "service_role";

revoke references on table "public"."users_table" from "service_role";

revoke select on table "public"."users_table" from "service_role";

revoke trigger on table "public"."users_table" from "service_role";

revoke truncate on table "public"."users_table" from "service_role";

revoke update on table "public"."users_table" from "service_role";

alter table "public"."users_table" drop constraint "users_table_pkey";

drop index if exists "public"."users_table_pkey";

drop table "public"."users_table";

create table "public"."collections_table" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "description" text,
    "uuid" uuid not null default gen_random_uuid()
);


alter sequence "public"."users_table_id_seq" owned by "public"."collections_table"."id";

CREATE UNIQUE INDEX users_table_pkey ON public.collections_table USING btree (id);

alter table "public"."collections_table" add constraint "users_table_pkey" PRIMARY KEY using index "users_table_pkey";

grant delete on table "public"."collections_table" to "anon";

grant insert on table "public"."collections_table" to "anon";

grant references on table "public"."collections_table" to "anon";

grant select on table "public"."collections_table" to "anon";

grant trigger on table "public"."collections_table" to "anon";

grant truncate on table "public"."collections_table" to "anon";

grant update on table "public"."collections_table" to "anon";

grant delete on table "public"."collections_table" to "authenticated";

grant insert on table "public"."collections_table" to "authenticated";

grant references on table "public"."collections_table" to "authenticated";

grant select on table "public"."collections_table" to "authenticated";

grant trigger on table "public"."collections_table" to "authenticated";

grant truncate on table "public"."collections_table" to "authenticated";

grant update on table "public"."collections_table" to "authenticated";

grant delete on table "public"."collections_table" to "service_role";

grant insert on table "public"."collections_table" to "service_role";

grant references on table "public"."collections_table" to "service_role";

grant select on table "public"."collections_table" to "service_role";

grant trigger on table "public"."collections_table" to "service_role";

grant truncate on table "public"."collections_table" to "service_role";

grant update on table "public"."collections_table" to "service_role";


